# Generated by Django 5.2.15 on 2026-10-06 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=20, unique=True, verbose_name='número de pedido')),
                ('client_name', models.CharField(max_length=200, verbose_name='nombre del cliente')),
                ('client_email', models.EmailField(max_length=254, verbose_name='email del cliente')),
                ('client_phone', models.CharField(blank=True, max_length=20, verbose_name='teléfono')),
                ('shipping_address', models.TextField(verbose_name='dirección de envío')),
                ('shipping_city', models.CharField(blank=True, max_length=100, verbose_name='ciudad')),
                ('shipping_postal_code', models.CharField(blank=True, max_length=20, verbose_name='código postal')),
                ('shipping_country', models.CharField(blank=True, default='Colombia', max_length=100, verbose_name='país')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='subtotal')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='costo de envío')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='impuestos')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='descuento')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('enviado', 'Enviado'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='estado')),
                ('payment_status', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('fallido', 'Fallido'), ('reembolsado', 'Reembolsado')], default='pendiente', max_length=20, verbose_name='estado de pago')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='método de pago')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='ID de transacción')),
                ('notes', models.TextField(blank=True, verbose_name='notas internas')),
                ('customer_notes', models.TextField(blank=True, verbose_name='notas del cliente')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='enviado el')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='entregado el')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='nombre del producto')),
                ('product_sku', models.CharField(blank=True, max_length=100, verbose_name='SKU')),
                ('brand_name', models.CharField(blank=True, max_length=100, verbose_name='marca')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio unitario')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='precio con descuento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.order', verbose_name='pedido')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.product', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'item del pedido',
                'verbose_name_plural': 'items del pedido',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-created_at'], name='cart_order_created_05c072_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='cart_order_status_a729d1_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created_at'], name='cart_order_user_id_6786ca_idx'),
        ),
    ]
