# Generated by Django 5.2.15 on 2026-09-30 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'lista de deseos',
                'verbose_name_plural': 'listas de deseos',
            },
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='añadido el')),
                ('notify_price_drop', models.BooleanField(default=True, verbose_name='notificar bajada de precio')),
                ('notify_back_in_stock', models.BooleanField(default=True, verbose_name='notificar disponibilidad')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to='catalog.product', verbose_name='producto')),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wishlist.wishlist', verbose_name='lista de deseos')),
            ],
            options={
                'verbose_name': 'item de lista de deseos',
                'verbose_name_plural': 'items de lista de deseos',
                'ordering': ['-added_at'],
                'unique_together': {('wishlist', 'product')},
            },
        ),
    ]
